# Generated by Django 6.0.2 on 2026-09-11 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / propósito')),
                ('icon', models.CharField(default='bi-people-fill', help_text='Clase de Bootstrap Icons, por ejemplo: bi-megaphone-fill', max_length=60, verbose_name='Ícono')),
                ('color', models.CharField(default='#213a5c', help_text='Color hexadecimal, por ejemplo: #8b5cf6', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_coordinados', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador (usuario)')),
            ],
            options={
                'verbose_name': 'Comité',
                'verbose_name_plural': 'Comités',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Organización / Institución')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('tipo', models.CharField(choices=[('ASOCIADO', 'Asociado'), ('ALIADO', 'Aliado / Contacto externo'), ('VOLUNTARIO', 'Voluntario'), ('INSTITUCION', 'Institución'), ('PROVEEDOR', 'Proveedor'), ('OTRO', 'Otro')], default='ASOCIADO', max_length=20, verbose_name='Tipo')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Opcional. Vincula esta persona con una cuenta existente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_crm', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de la plataforma')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('IDEA', 'Idea'), ('PLANEACION', 'En planeación'), ('EN_CURSO', 'En curso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='IDEA', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comite', models.ForeignKey(blank=True, help_text='Dejar vacío para un proyecto transversal de la Asociación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='gestion.comite', verbose_name='Comité')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_liderados', to='gestion.persona', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('EN_REVISION', 'En revisión'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='gestion.persona', verbose_name='Asignada a')),
                ('comite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestion.comite', verbose_name='Comité')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['due_date', '-prioridad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.comite')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.persona')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.proyecto')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.tarea')),
            ],
            options={
                'verbose_name': 'Nota de seguimiento',
                'verbose_name_plural': 'Notas de seguimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MiembroComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('COORDINADOR', 'Coordinador(a)'), ('SECRETARIO', 'Secretario(a)'), ('MIEMBRO', 'Miembro'), ('COLABORADOR', 'Colaborador(a)')], default='MIEMBRO', max_length=20, verbose_name='Rol')),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='gestion.comite')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='gestion.persona')),
            ],
            options={
                'verbose_name': 'Miembro de comité',
                'verbose_name_plural': 'Miembros de comités',
                'ordering': ['rol', 'persona__first_name'],
                'unique_together': {('comite', 'persona')},
            },
        ),
    ]
