# Generated by Django 6.0.2 on 2026-09-11 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_seed_comites'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='avance',
            field=models.PositiveSmallIntegerField(default=0, help_text='Se usa mientras el proyecto no tenga tareas; con tareas el avance se calcula automáticamente.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Avance reportado (%)'),
        ),
    ]
