# Generated by Django 6.0 on 2026-01-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('photo', models.ImageField(upload_to='featured_members/', verbose_name='Foto')),
                ('association_position', models.CharField(help_text='Ej: Presidente, Vicepresidente, Director Científico', max_length=150, verbose_name='Cargo en la Asociación')),
                ('profession', models.CharField(help_text='Ej: Ingeniero Nuclear, Físico Médico', max_length=150, verbose_name='Profesión')),
                ('professional_trajectory', models.TextField(help_text='Descripción de la experiencia y logros profesionales', verbose_name='Trayectoria Profesional')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Perfil de LinkedIn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Los asociados se mostrarán ordenados de menor a mayor', verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asociado Destacado',
                'verbose_name_plural': 'Asociados Destacados',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
