# Generated by Django 6.0 on 2026-03-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('ASSOCIATION', 'De la Asociación'), ('NUCLEAR', 'Temática Nuclear')], default='NUCLEAR', help_text='Selecciona si es una noticia de la asociación o sobre temática nuclear', max_length=15, verbose_name='Categoría'),
        ),
    ]
