# Generated by Django 6.0 on 2026-03-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_add_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredmember',
            name='is_international',
            field=models.BooleanField(default=False, help_text='Marcar si es un asociado o colaborador internacional', verbose_name='Asociado Internacional'),
        ),
    ]
