# Generated by Django 6.0 on 2026-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_add_international_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredmember',
            name='association_position_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si se deja vacío, se muestra el español.', max_length=150, verbose_name='Cargo en la Asociación (inglés)'),
        ),
        migrations.AddField(
            model_name='featuredmember',
            name='profession_en',
            field=models.CharField(blank=True, help_text='Versión en inglés. Si se deja vacío, se muestra el español.', max_length=150, verbose_name='Profesión (inglés)'),
        ),
        migrations.AddField(
            model_name='featuredmember',
            name='professional_trajectory_en',
            field=models.TextField(blank=True, help_text='Versión en inglés. Si se deja vacío, se muestra el español.', verbose_name='Trayectoria Profesional (inglés)'),
        ),
    ]
