# Generated by Django 6.0.2 on 2026-10-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_is_international_to_is_advisory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('event_type', models.CharField(choices=[('CONFERENCE', 'Conferencia'), ('WEBINAR', 'Webinar'), ('WORKSHOP', 'Taller'), ('NETWORKING', 'Encuentro'), ('OTHER', 'Evento')], default='CONFERENCE', max_length=20, verbose_name='Tipo de evento')),
                ('modality', models.CharField(choices=[('IN_PERSON', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'Híbrido')], default='IN_PERSON', max_length=20, verbose_name='Modalidad')),
                ('starts_at', models.DateTimeField(verbose_name='Inicio')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Opcional. Sin hora de fin, el evento se muestra como próximo hasta el final de su día.', null=True, verbose_name='Fin')),
                ('location', models.CharField(blank=True, help_text='En eventos virtuales, la plataforma (Zoom, Meet, YouTube...).', max_length=200, verbose_name='Lugar')),
                ('summary', models.CharField(help_text='Una o dos frases. Se muestran en la portada y en la agenda.', max_length=280, verbose_name='Resumen')),
                ('description', models.TextField(blank=True, help_text='Programa, ponentes, requisitos. Texto simple: los saltos de línea se respetan.', verbose_name='Descripción')),
                ('cover_image', models.ImageField(blank=True, upload_to='events/', verbose_name='Imagen')),
                ('registration_url', models.URLField(blank=True, help_text='Formulario de inscripción o enlace de acceso a la transmisión.', verbose_name='Enlace de inscripción')),
                ('is_published', models.BooleanField(default=True, help_text='Desmárcalo para guardarlo como borrador sin mostrarlo en el sitio.', verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-starts_at'],
            },
        ),
    ]
