# Generated by Django 6.0 on 2026-01-26 00:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0003_alter_membershipapplication_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único para URL de verificación', unique=True)),
                ('card_number', models.CharField(help_text='Formato: ASNC-YYYY-NNNN', max_length=20, unique=True, verbose_name='Número de Carné')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='carnets/photos/', verbose_name='Foto')),
                ('category', models.CharField(choices=[('FOUNDER', 'Fundador'), ('ASSOCIATE', 'Asociado')], default='ASSOCIATE', max_length=20, verbose_name='Categoría')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('expiry_date', models.DateField(help_text='Por defecto: 31 de diciembre del año de emisión', verbose_name='Fecha de Vencimiento')),
                ('status', models.CharField(choices=[('PENDING_PHOTO', 'Pendiente de Foto'), ('ACTIVE', 'Activo'), ('EXPIRED', 'Expirado'), ('SUSPENDED', 'Suspendido'), ('CANCELLED', 'Cancelado')], default='PENDING_PHOTO', max_length=20, verbose_name='Estado')),
                ('photo_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token único para subir foto', unique=True)),
                ('photo_token_used', models.BooleanField(default=False, verbose_name='Token de foto usado')),
                ('suspension_reason', models.TextField(blank=True, verbose_name='Motivo de suspensión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_card', to='admissions.membershipapplication', verbose_name='Solicitud de Ingreso')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_cards', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_card', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carné Digital',
                'verbose_name_plural': 'Carnés Digitales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='Verificado en')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='carnets.membercard', verbose_name='Carné')),
            ],
            options={
                'verbose_name': 'Verificación de Carné',
                'verbose_name_plural': 'Verificaciones de Carnés',
                'ordering': ['-verified_at'],
            },
        ),
    ]
