# Generated by Django 6.0 on 2026-01-30 02:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membercard',
            name='photo_token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación del token para control de expiración', verbose_name='Token creado en'),
        ),
        migrations.AlterField(
            model_name='membercard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='member_card', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
