# Generated by Django 6.0 on 2025-12-20 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('profession', models.CharField(max_length=100, verbose_name='Profesión / Título')),
                ('current_job', models.CharField(blank=True, max_length=100, verbose_name='Cargo Actual')),
                ('institution', models.CharField(blank=True, max_length=100, verbose_name='Empresa / Institución')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn / Perfil Profesional')),
                ('cv_file', models.FileField(upload_to='applications/cvs/', verbose_name='Hoja de Vida (PDF)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('REVIEW', 'En Estudio'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('COMPLETED', 'Vinculado (Usuario Creado)')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas Internas del Comité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Ingreso',
                'verbose_name_plural': 'Solicitudes de Ingreso',
                'ordering': ['-created_at'],
            },
        ),
    ]
