# Generated by Django 6.0 on 2026-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='contribution_statement',
            field=models.TextField(blank=True, help_text='Cuéntanos brevemente sobre ti, tu experiencia en el sector nuclear y cómo crees que puedes contribuir al crecimiento de la asociación.', verbose_name='¿Cómo puedes aportar a la ASNC?'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/cvs/', verbose_name='Hoja de Vida (PDF)'),
        ),
    ]
