# Generated by Django 6.0 on 2026-01-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_add_contribution_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
