# Generated by Django 6.0 on 2026-06-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_membershipapplication_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='contactado',
            field=models.BooleanField(default=False, verbose_name='Contactado'),
        ),
    ]
