# Generated by Django 6.0 on 2026-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_membershipapplication_contactado'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='sector',
            field=models.CharField(blank=True, choices=[('ENERGY', 'Energía y generación nuclear'), ('MEDICINE', 'Medicina e imagenología nuclear'), ('REGULATION', 'Regulación y seguridad nuclear'), ('RESEARCH', 'Investigación y academia'), ('INDUSTRY', 'Industria y aplicaciones industriales'), ('RADIOPROTECTION', 'Protección radiológica'), ('WASTE', 'Gestión de residuos radiactivos'), ('AGRICULTURE', 'Agricultura y alimentos'), ('MINING', 'Minería y materiales radiactivos'), ('ENVIRONMENT', 'Medio ambiente'), ('GOVERNMENT', 'Gobierno y política pública'), ('OTHER', 'Otro')], max_length=20, verbose_name='Sector'),
        ),
    ]
