# Generated by Django 6.0 on 2026-06-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_membershipapplication_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='sector',
            field=models.CharField(blank=True, choices=[('MINING', 'Sector Minero'), ('OIL_GAS', 'Oil and Gas'), ('ENERGY', 'Sector Energético'), ('AGRO', 'Agroindustria / Alimentos'), ('HEALTH', 'Sector Salud'), ('ACADEMIA', 'Academia'), ('REGULATORY', 'Sector Regulatorio'), ('OTHER', 'Otros')], max_length=20, verbose_name='Sector'),
        ),
    ]
