# Generated by Django 6.0 on 2026-01-25 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('recipients', models.TextField(help_text='Lista de correos separados por coma', verbose_name='Destinatarios')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de destinatarios')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('success', models.BooleanField(default=True, verbose_name='Enviado exitosamente')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Correo Enviado',
                'verbose_name_plural': 'Correos Enviados',
                'ordering': ['-sent_at'],
            },
        ),
    ]
